app/models/consignment.py
from .address import Address
from enum import Enum
from app import db
from datetime import datetime
import pytz
timezone = pytz.timezone("Asia/Kolkata")

join_table = db.Table(
    'join_table', db.Model.metadata, db.Column(
        'consignmentID', db.Integer, db.ForeignKey('consignment.id')),
    db.Column('truckID', db.Integer, db.ForeignKey('truck.id')))


class ConsignmentStatus(Enum):
    PENDING = 0
    ENROUTE = 1
    ALLOTED = 2
    DELIVERED = 3


class Consignment(db.Model):
    """
        A class for representing a consignment
        ....

        Attributes
        ----------
        volume: int
            volume of the consignment

        senderAddress: Address
            address of the sender of the consignment

        receiverAddress: Address
            address of the receiver of the consignment

        srcBranchID: int
            id of the office where the consignment was placed

        dstBranchID: int
            id of the destination office of the consignment

        trucks: Truck
            list of the trucks on which the consignment was loaded

        Member Functions
        ----------------
        getInvoice(): dict

        __repr__(): str
            returns the string representation of an object of the class

    """
    ####################################### ORM ##############################################
    __tablename__ = "consignment"

    id = db.Column(db.Integer, primary_key=True)

    volume = db.Column(db.Integer, index=True)
    status = db.Column(db.Enum(ConsignmentStatus), index=True)

    placetime = db.Column(db.DateTime)
    dispatchtime = db.Column(db.DateTime)
    arrivaltime = db.Column(db.DateTime)

    charge = db.Column(db.Integer, index=True)

    # invoice = db.relationship('Bill',uselist = False,lazy = False)

    senderID = db.Column(db.Integer, db.ForeignKey('address.id'))
    receiverID = db.Column(db.Integer, db.ForeignKey('address.id'))
    senderName = db.Column(db.String(64))
    senderAddress = db.relationship(
        'Address', uselist=False, foreign_keys=senderID)
    receiverName = db.Column(db.String(64))
    receiverAddress = db.relationship(
        'Address', uselist=False, foreign_keys=receiverID)

    srcBranchID = db.Column(db.Integer, db.ForeignKey("office.id"), index=True)
    dstBranchID = db.Column(db.Integer, db.ForeignKey("office.id"), index=True)

    billID = db.Column(db.Integer, db.ForeignKey('bill.id'))
    bill = db.relationship(
        'Bill', uselist=False, foreign_keys=billID)

    trucks = db.relationship(
        "Truck", secondary=join_table, back_populates="consignments")

    ############################################################################################
    def __init__(self, **kwargs) -> None:
        '''
            The constructor of the consignment class
            ....

            Parameters:
                volume: int 
                    volume of the consignment
                senderAddress: Address
                    address of the sender of the consignment
                receiverAddress: Address
                    address of the receiver of the consignment
                srcBranchID: int
                    id of the office where the consignment was placed
                dstBranchID: int
                    id of the destination office of the consignment

        '''

        super().__init__(**kwargs)
        self.status = ConsignmentStatus.PENDING
        self.charge = 0
        self.placetime = timezone.localize(datetime.now())

    def getInvoice(self) -> dict:
        res = {
            "volume": self.volume,
            "placetime": self.placetime,
            "charge": self.charge,
            "sender": {
                "name": self.senderName,
                "city": self.senderAddress.city,
                "address": self.senderAddress.addrLine,
                "zipCode": self.senderAddress.zipCode
            },
            "receiver": {
                "name": self.receiverName,
                "city": self.receiverAddress.city,
                "address": self.receiverAddress.addrLine,
                "zipCode": self.receiverAddress.zipCode
            }
        }

        return res

    def __repr__(self) -> str:
        """
            The function to get the string representation of the consignment
            ....

            Returns:
                str
        """
        return f'<Consignment: {self.id}, Volume:{self.volume}, status: {self.status}>'

app/models/rate.py
{
    'rate':5.0
}

app/truck/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, ValidationError
from app.models import Office,Truck


class TruckForm(FlaskForm):
    '''

    '''
    plateNo = StringField("Plate No.", validators=[DataRequired()])
    branch = SelectField("Branch", coerce=int)
    submit = SubmitField("Create")

    def validate_plateNo(self, field):
        t = Truck.query.filter_by(plateNo=field.data).first()
        if t is not None:
            raise ValidationError('Truck already registered.')

    def __init__(self, **kwargs):
        '''
        '''
        super().__init__(**kwargs)
        self.branch.choices = [(x.id, f'{x.address.city} Office')
                               for x in Office.query.order_by("id")]


class ReceiveTruckForm(FlaskForm):
    '''

    '''
    plateNo = SelectField("Plate No.", coerce=int)
    submit = SubmitField("Receive")

    def __init__(self, branchID, **kwargs):
        '''
        '''
        super().__init__(**kwargs)
        self.branchID = branchID
        self.plateNo.choices = [(x.id, f'{x.plateNo}')
                               for x in Truck.query.filter_by(dstBranchID=self.branchID) if x.status.name=="ENROUTE"]

app/routes.py
from flask.blueprints import Blueprint
from flask import render_template, flash, url_for
from flask_login import current_user, login_required
from werkzeug.utils import redirect
from werkzeug.urls import url_parse
from app.models import Consignment, BranchOffice, Truck, Office
from app import db
from .forms import ChangeRate

main = Blueprint("main", import_name=__name__, template_folder="templates")


@main.route('/')
def about():
    '''
        The function displays the About page of the website to the user
    '''
    return render_template("about.html", title="TL;DR"), 200


@main.route('/home')
@login_required
def home():
    '''
        The function displays the Home page of the website to the user
    '''
    return render_template(f"{current_user.role}.html", title='TL;DR'), 200


@main.route('/branch/view/all')
@login_required
def branch_all():
    '''
        If the user is the manager, this function allows him to view the records of all the branches
        Else the access is forbidden and error 403 is displayed
    '''
    if current_user.role == "manager":
        branches = Office.query.all()
        return render_template('branches.html', data=branches), 200

    return render_template('errors/403.html'), 403


@main.route('/branch/rate', methods=["GET", "POST"])
@login_required
def change_rate():
    if current_user.role == "manager":
        form = ChangeRate()
        if form.validate_on_submit():
            Office.setRate(form.rate.data)
            flash("Rate value changed", 'success')
            return redirect(url_for("main.home"), code=302)
        return render_template("rate.html", form=form,rate = Office.getRate()), 200

    return render_template('errors/403.html'), 403


@main.route('/branch/view/<token>')
@login_required
def branch(token):
    '''
        If the user is an employee, access is denied to him and error 403 is displayed
        Else the user is redirected to a page where all the records of the office, 
                with the given token as id, are displayed
        ....

        Parameters: 
            token: int
                stores the id of the branch which is enquired

    '''
    if current_user.role == "manager":
        branch = Office.query.filter_by(id=token).first()
        labels = [x.time for x in branch.waitingtime]
        values = [x.value for x in branch.waitingtime]
        revenue = round(branch.getRevenue())

        return render_template('branch.html', name=branch.address.city, trck=branch.trucks, consign=branch.consignments, revenue=revenue, labels=labels, values=values), 200
    return render_template('errors/403.html'), 403

app/truck/__init__.py
from flask import Blueprint

truck = Blueprint("truck", __name__,
                 template_folder="../templates/truck", url_prefix="/truck")
from app.truck import routes

app/truck/routes.py
from app.truck import truck
from flask import redirect, url_for, flash, current_app, request, render_template
from flask_login import current_user, login_required
from app import db, mail
from app.models import Office, Consignment, Address, Truck, Manager, TruckStatus
from .forms import TruckForm, ReceiveTruckForm
from flask_mail import Message
from datetime import datetime


@truck.route("/view/all", methods=["GET"])
@login_required
def view_all():
    x = 1
    if current_user.role == "manager":
        trucks = Truck.query.all()
    elif current_user.role == "employee":
        trucks = Truck.query.filter_by(branchID=current_user.branchID)
    if trucks is None:
        x = 0
    trucks = [(x, Office.query.get(x.branchID).address.city + " Office")
              for x in trucks]
    return render_template("view_all.html", data=trucks, len=x), 200


@truck.route("/view/<id>", methods=["GET"])
@login_required
def view(id):
    truck_ = Truck.query.get(id)

    if truck_ is not None:
        consigns = truck_.consignments
        x = len(consigns)

        ts = [x.time for x in truck_.usage]
        value = [x.value for x in truck_.usage]
        ts2 = [x.time for x in truck_.idle]

        value2 = [x.value for x in truck_.idle]

        destination = (Office.query.get(truck_.dstBranchID).address.city +
                       " Office") if truck_.dstBranchID is not None else "Not Assigned yet"
        branchName = Office.query.get(truck_.branchID).address.city + " Office"
        return render_template("truck.html", role=current_user.role, truck=truck_, data=consigns, len=x, values=value, labels=ts, values2=value2, labels2=ts2,
                               destination=destination, branchName=branchName), 200
    flash("Truck not registered", "warning")
    return redirect(url_for("main.home"), code=302)


@truck.route("/dispatch/view", methods=["GET"])
@login_required
def dispatch():
    trucks = Truck.query.filter_by(branchID=current_user.branchID)
    readyTrucks = []
    for i in trucks:
        if i.status == TruckStatus.READY:
            readyTrucks.append(i)
            print(i.status)
    x = len(readyTrucks)
    return render_template("dispatch.html", data=readyTrucks, len=x), 200


@truck.route("/dispatch/<id>")
@login_required
def dispatch_truck(id):

    truck_ = Truck.query.get(id)
    branch = Office.query.get(current_user.branchID)

    branch.dispatchTruck(truck_)
    db.session.commit()

    ################### SHOW DETAILS OF ALL CONSIGNMENTS IN SIDE IT BEFORE DISPATCH ###################
    flash("Truck Logged as dispatched", "info")
    return redirect(url_for("main.home"))


@truck.route("/request-for", methods=['GET', 'POST'])
@login_required
def request_truck():
    '''

    '''
    if current_user.role == "manager":
        # flash('Access Denied', 'warning')
        # return redirect(url_for('main.home', role=current_user.role), code=302)
        return render_template('errors/403.html'), 403

    manager = Manager.query.filter_by(role="manager").first()
    office = Office.query.filter_by(id=current_user.branchID).first()

    msg = Message('Buy New Truck Request',
                  sender=current_app.config['MAIL_USERNAME'],
                  recipients=[manager.email],
                  body=render_template("request_truck.txt", user=manager, branch=office))
    mail.send(msg)

    flash('Request mail sent!', 'success')
    return redirect(url_for('main.home', role=current_user.role), code=302)


@truck.route("/add", methods=["GET", "POST"])
@login_required
def add():
    '''

    '''
    if current_user.role == "employee":
        return render_template('errors/403.html'), 403

    if current_user.role == "manager":

        form = TruckForm()
        if form.validate_on_submit():

            truck_ = Truck(plateNo=form.plateNo.data)
            db.session.add(truck_)
            db.session.commit()

            branch = Office.query.get(form.branch.data)
            branch.addTruck(truck_)

            db.session.commit()
            
            Office.allotTruck(branch)
            db.session.commit()

            flash("Truck Added", 'success')
            return redirect(url_for("main.home"), code=302)

        return render_template("add.html", title="Buy new truck", form=form), 200


@truck.route("/receive", methods=["GET", "POST"])
@login_required
def receive():
    if current_user.role == "manager":
        return render_template('errors/403.html'), 403
    form = ReceiveTruckForm(current_user.branchID)
    if form.validate_on_submit():
        truck_ = Truck.query.filter_by(id=form.plateNo.data).first()
        if truck_ is None or truck_.dstBranchID != current_user.branchID or truck_.status.name != "ENROUTE":
            flash("Bad request: truck not found/not applicable", 'warning')
            return redirect(url_for("main.home"), code=302)

        branch = Office.query.filter_by(id=current_user.branchID).first()
        branch.receiveTruck(truck_)
        db.session.commit()

        Office.allotTruck(branch)
        db.session.commit()

        flash("Truck logged as received", 'info')
        return redirect(url_for("main.home"), code=302)
    return render_template('receive.html', form=form, title="Receive Truck"), 200

app/templates/about.html
{% extends "auth/layout.html" %}
{% block bg%}
<img src="{{ url_for('static',filename = 'tccs_.png') }}" alt="" style="width: fit-content; padding-left: 155px;">
{% endblock %}

app/templates/base.html
<html>
<head>
    {% if title %}
    <title>{{ title }} - Microblog</title>
    {% else %}
    <title>Nameless</title>
    {% endif %}
</head>

<body>
    <div>Application:
        <a href="{{ url_for('main.about') }}"">About</a>
        {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Login</a>
        {% else %}
        <a href="{{ url_for('main.home',role = current_user.role) }}">Home</a>
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% endif %}
    </div>
    <div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
    </div>
    <hr>
    {% block content %}{% endblock %}
</body>

</html>

app/templates/branch.html
{% extends "auth/layout.html" %}
{% block content %}
<h1>Branch {{ name }} Office</h1>
<h2>Revenue: {{ revenue }}</h2>
{% if trck %}
<h2>Trucks in the branch are:</h2>
<div class="container cont">
    {% for data in trck %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='truck.png') }}" alt=""></div>
        <div class="content">
            <h2>Truck ID: {{ data.id }}</h2>
            <h3>Plate No.: {{ data.plateNo }}</h3>
            <p>Status: {{ data.status.name }}</p>
            <p>Consignments: {{ data.consignments|count }}
            </p>
            <button class="ghost-btn" onclick="location.href='/truck/view/{{ data.id }}';">Go to this truck page</button>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h2>No trucks in the branch</h2>
{% endif %}
<br>
{% if consign %}
<h2>Consignments in the branch are:</h2>
<div class="container cont">
    {% for data in consign %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='consign.png') }}" alt="">
        </div>
        <div class="content">
            <h2>Consignment ID: {{ data.id }}</h2>
            <h3>Branch: {{ data.srcBranchId }}</h3>
            <p>Status: {{ data.status.name }}</p>
            <p>Volume: {{ data.volume }}</p>
            <button class="ghost-btn" onclick="location.href='/consign/view/{{ data.id }}';">View Bill</button>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<h2>No consignments in the branch</h2>
{% endif %}
<br>

<h2>Average Consignment Waiting Period</h2>
<div class = "container cont">
<canvas id="myChart" width="600" height="400"></canvas>
<script>
    var timeFormat = 'MMMM Do YYYY, h:mm:ss a';

function newDateString(hours, minutes, seconds, date, month, year) {
    return moment().hour(hours).minute(minutes).second(seconds).date(date).month(month).year(year).format(timeFormat);
}


var chartData = {
    labels: [{% for item in labels %}
newDateString({{ item.hour }}, {{ item.minute }}, {{ item.second }}, {{ item.day }}, {{ item.month }}, {{ item.year }}),
    {% endfor %}],
datasets: [{
    label: 'Average Waiting Period',
    fill: true,
    lineTension: 0.1,
    backgroundColor: "rgba(75,192,192,0.4)",
    borderColor: "rgba(75,192,192,1)",
    borderCapStyle: 'butt',
    borderDash: [],
    borderDashOffset: 0.0,
    borderJoinStyle: 'miter',
    pointBorderColor: "rgba(75,192,192,1)",
    pointBackgroundColor: "#fff",
    pointBorderWidth: 1,
    pointHoverRadius: 5,
    pointHoverBackgroundColor: "rgba(75,192,192,1)",
    pointHoverBorderColor: "rgba(220,220,220,1)",
    pointHoverBorderWidth: 2,
    pointRadius: 1,
    pointHitRadius: 10,
    data: [{% for item in values %}
                  {{ item }},
{% endfor %}],
    spanGaps: false
    }]
  }

// get chart canvas
var ctx = document.getElementById("myChart").getContext("2d");

// create the chart using the chart canvas
var myChart = new Chart(ctx, {
    type: 'line',
    data: chartData,
});
</script>
</div>
<br>
<br>
{% endblock %}

app/templates/branches.html
{% extends "auth/layout.html" %}
{% block content %}
<br>
<div class="container cont">
    {% if data %}
    {% for data in data %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='office.png') }}" alt=""></div>
        <div class="content">
            <h2>Branch ID: {{ data.id }}</h2>
            <h3>City: {{ data.address.city }}</h3>
            <p>Consignments: {{ data.consignments|count }}
            </p>
            <p>Trucks: {{ data.trucks|count }}
            </p>
            
            <!-- <p>Revenue: {{ data.revenue }}</p> -->
            <button class="ghost-btn" onclick="location.href='/branch/view/{{ data.id }}';">Go to this branch page</button>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h2>No branch found</h2>
    {% endif %}
</div>
<br>
{% endblock %}

app/templates/consignments.html
{% extends "auth/layout.html" %}
{% block content %}
<div class="container cont">
    {% for data in data %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='consign.jpg') }}" alt=""></div>
        <div class="content">
            <h2>Consignment ID: {{ data.id }}</h2>
            <h3>Branch: {{ data.srcBranchID }}</h3>
            <p>Status: {{ data.status }}</p>
            <p>Volume: {{ data.volume }}</p>
            <p>Volume Left: {{ data.volumeLeft }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/employee.html
{% extends "auth/layout.html" %}

{% block content %}
{% if current_user.is_authenticated %}
<h1>Hello, {{ current_user.name }}! You are {{current_user.role}}.</h1>
<h3>What would you like to do?</h3>
{% endif %}
<div class="mngrcf container-fluid">
    <button type="button" class="button mngrbtn" onclick="location.href='/truck/view/all';"> View Trucks</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/consign/view/all';"> View Consignments</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/consign/';"> Place Consignment</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/truck/dispatch/view';"> Dispatch Truck</button>
    <button type="button" class="button mngrbtn" onclick="location.href='truck/receive';"> Receive Truck</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/truck/request-for';"> Request for Truck</button>
</div>
{% endblock %}

app/templates/index.html
{% extends "auth/layout.html" %}

{% block content %}
{% if current_user.is_authenticated %}
    <h1>Hello, {{ user.name }}! You are {{current_user.role}}.</h1>
{% else %}
    <h1>Hello anonymous user</h1>
{% endif %}
{% endblock %}

app/templates/login_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/manager.html
{% extends "auth/layout.html" %}


{% block content %}
<div style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
{% if current_user.is_authenticated %}
    <h1>Hello, {{ current_user.name }}!</h1>
    <h3>What would you like to do?</h3>
{% endif %}
</div >
<div class="mngrcf container-fluid">
    <button type="button" class="button mngrbtn" onclick="location.href='/truck/view/all';"> View Trucks</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/branch/view/all';"> View Branch Offices</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/consign/view/all';"> View Consignments</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/auth/register';"> Add Employee</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/truck/add';"> Buy New Truck</button>
    <button type="button" class="button mngrbtn" onclick="location.href='/branch/rate';"> Change Rate</button>
</div>
{% endblock %}

app/templates/rate.html
{% extends "consign/layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Change Rate</legend>
            <div class="form-group">
                <h3>Current Rate: {{ rate }}</h3>
                {{ form.rate.label(class = "form-control-label") }}
                {% if form.rate.errors %}
                    {{ form.rate(class = "form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.rate.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                {{ form.rate(class = "form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.employee_type.label(class="form-control-label") }}
                    {% if form.employee_type.errors %}
                        {{ form.employee_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.employee_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.employee_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

app/templates/truck.html
{% extends "auth/layout.html" %}
{% block content %}
<h1>Truck ID: {{ trck.id }}</h1>
<h3>Plate No.: {{ trck.plateNo }}</h3>
<h3>Branch ID: {{ trck.branchId }}</h3>
<h3>Status: {{ trck.status }}</h3>
<h2>Consignments in the truck are:</h2>
<div class="container cont">
    {% for data in consign %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='consign.jpg') }}" alt=""></div>
        <div class="content">
            <h2>Consignment ID: {{ data.id }}</h2>
            <h3>Branch: {{ data.srcBranchId }}</h3>
            <p>Status: {{ data.status }}</p>
            <p>Volume: {{ data.volume }}</p>
            <p>Volume Left: {{ data.volumeLeft }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/trucks.html
{% extends "auth/layout.html" %}
{% block content %}
<div class="container cont">
    {% for data in data %}
    <div class="box">
        <div class="img-box" title={{ data.id }}><img src="{{ url_for('static', filename='truck.jpg') }}" alt=""></div>
        <div class="content">
            <h2>Truck ID: {{ data.id }}</h2>
            <h3>Plate No.: {{ data.plateNo }}</h3>
            <h3>Branch: {{ data.branchID }}</h3>
            <p>Status: {{ data.status }}</p>
            <p>Consignment IDs:
                {% for cids in data.consignments %}
                {{ cids.id }}  
                {% endfor %}
            </p>
            <!-- <p>Revenue: {{ data.revenue }}</p> -->
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}